name: CI workflows (cl)

env:
  IMAGE_NAME: testcicd
  IMAGE_TAG: 1.1.0
  DOCKER_HUB_REGISTRY: hadjimansour

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $DOCKER_HUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Test Docker image
        run: docker image ls $DOCKER_HUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker image
        run: docker push $DOCKER_HUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
